name: Notesapp
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Docker Container
        run: |
          docker-compose up --detach 
      - name: Check cURL Request
        run: |
          curl -X GET http://localhost:8000/
      - name: Stop Docker Container
        run: docker-compose down