name: Notesapp

on:
  push:
    branches:
      - index  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb

      - name: Start MongoDB
        run: |
          sudo systemctl start mongodb

      - name: Start FastAPI
        run: |
          nohup uvicorn index:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
          echo $! > fastapi.pid  # Save the PID of the FastAPI process

      - name: Print FastAPI Logs
        run: cat fastapi.log

      - name: Wait for processes to start
        run: sleep 30s

      - name: Check cURL Request
        run: |
          curl -v http://localhost:8000/

      - name: Cleanup
        run: |
          kill $(cat fastapi.pid) || true
          sudo systemctl stop mongodb || true
