name: Notesapp

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb

      - name: Start FastAPI and MongoDB
        run: |
          nohup uvicorn index:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &

      - name: Print FastAPI Logs
        run: cat fastapi.log

      - name: Wait for processes to start
        run: sleep 30s

      - name: Check cURL Request
        run: |
          curl -v http://localhost:8000/

      - name: Cleanup
        run: killall -q uvicorn || true
