name: Notesapp

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt  # Adjust based on your project's requirements
          pip3 install fastapi uvicorn pymongo  # Install FastAPI and MongoDB driver

      - name: Start FastAPI and MongoDB as background processes
        run: |
          nohup uvicorn index:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &  # Redirect FastAPI logs to a file
          mongod --fork --logpath /var/log/mongodb.log > mongodb.log 2>&1 &  # Redirect MongoDB logs to a file

      - name: Print FastAPI Logs
        run: cat fastapi.log

      - name: Print MongoDB Logs
        run: cat mongodb.log

      - name: Wait for processes to start
        run: sleep 30s

      - name: Check cURL Request
        run: |
          curl -X GET http://localhost:8000/

      - name: Cleanup
        run: |
          killall -q uvicorn mongod || true

      - name: Wait for processes to stop
        run: sleep 10s
