name: Notesapp

on:
 - 'push'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v2
 
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
 
     - name: Install dependencies
       run: |
         pip install --upgrade pip
         pip install -r requirements.txt
     - name: Install MongoDB
       uses: supercharge/mongodb-github-action@1.10.0
 
     - name: Run FastAPI Tests
       run: |
         nohup uvicorn myapp.index:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
         echo $! > fastapi.pid # Save the PID of the FastAPI process
         sleep 30s # Wait for FastAPI to start
         # Add your tests here, e.g., cURL requests or use a testing framework
         curl -X GET http://localhost:8000/
         # Don't forget to stop the FastAPI server if it is no longer needed
         kill $(cat fastapi.pid) || true
 