name: FastAPI Workflow

on:
  - 'push'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn
          pip install "pymongo[srv]"

      - name: Set up MongoDB connection
        run: |
          echo "MONGO_URI=mongodb+srv://harshithkumar6510:harshithkumar6510@cluster0.uomdcii.mongodb.net/" >> $GITHUB_ENV

      - name: Run FastAPI application
        run: |
          uvicorn index:app --host 0.0.0.0 --port 8000
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Check endpoint with curl
        run: |
          curl -X GET http://localhost:8000/

